;
; Netatalk 4.x configuration file
;

; Global server settings
[Global]
afp listen = 172.29.60.1 172.29.61.1
hostname = vmacsrv
fqdn = vmacsrv.vintage.macgeek.home
appletalk = yes
server name = Vintage Mac File Server
uam list = uams_guest.so uams_randnum.so uams_dhx.so uams_dhx2.so

force user = 9999
force group = 9999

log file = /proc/1/fd/1
log level = default:info


; dircachesize = 8192
; dircache files = no
; dircache validation freq = 1
; dircache metadata window = 300
; dircache metadata threshold = 60

; legacy icon = 
; login message = 
; mimic model = 

; [Homes]
; basedir regex = /home

[software]
cnid scheme = dbd
ea = ad
path = /mnt/software
volume name = software
valid users = afpuser 
rwlist = afpuser 

[data]
cnid scheme = dbd
ea = ad
path = /mnt/data
volume name = data
valid users = afpuser 
rwlist = afpuser 
