# AppleTalk daemon configuration (netatalk 4.x)
#
# See the `atalkd.conf' manual page for examples.
vintagehost_if -seed -phase 2 -net 60 -addr 60.1 -zone "EtherTalk zone"
ethoudp_tap -seed -phase 2 -net 61 -addr 61.1 -zone "EthOverUDP zone"
